# Enhanced Pages CMS Configuration for AG Computational Arithmetic Geometry
# This file configures the content management interface at https://app.pagescms.org/
# Updated January 2025 - Fully aligned with latest PagesCMS features and actual content

# Media Configuration
media:
  - name: images
    label: Images & Photos
    input: assets/img
    output: /assets/img
    path: assets/img
    categories: [image]
    extensions: [jpg, jpeg, png, gif, svg, webp]
    description: "Upload images for team members, research areas, and general website content"
  - name: documents
    label: Documents & PDFs
    input: assets/uploads
    output: /assets/uploads
    path: assets/uploads
    categories: [document]
    extensions: [pdf, doc, docx, ppt, pptx, xls, xlsx, txt, md, tex, bib]
    description: "Course materials, announcements, and research documents"


# Content Types Configuration
content:
  # Publications - NEW: Full collection management
  - name: publications
    label: Publications
    type: collection
    path: _publications
    filename: "{year}-{title|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [title, authors, year, type, status, featured]
      primary: title
      sort:
        field: year
        direction: desc
      search: [title, authors, abstract, keywords]
      filters:
        - field: type
          label: Publication Type
        - field: status
          label: Status
        - field: featured
          label: Featured
      group_by: year
    fields:
      - name: layout
        label: Layout
        type: string
        default: publication
        hidden: true
      - name: title
        label: Publication Title
        type: string
        required: true
        description: "Full title of the publication"
        validation:
          min_length: 5
          max_length: 500
      - name: authors
        label: Authors
        type: string
        required: true
        description: "Author names separated by commas"
        validation:
          min_length: 2
          max_length: 200
      - name: year
        label: Publication Year
        type: number
        required: true
        description: "Year of publication"
        validation:
          min: 1900
          max: 2030
      - name: type
        label: Publication Type
        type: select
        required: true
        options:
          "Journal Article": Journal Article
          "Preprint": Preprint
          "Conference Paper": Conference Paper
          "Book": Book
          "Book Chapter": Book Chapter
          "Thesis": Thesis
          "Software": Software
          "Technical Report": Technical Report
        default: "Journal Article"
        description: "Type of publication"
      - name: status
        label: Publication Status
        type: select
        options:
          "Published": Published
          "Submitted": Submitted
          "Under Review": Under Review
          "In Preparation": In Preparation
          "Accepted": Accepted
        default: "Published"
        description: "Current status of the publication"
      - name: journal
        label: Journal/Conference/Publisher
        type: string
        description: "Journal name, conference name, or publisher"
        validation:
          max_length: 200
      - name: abstract
        label: Abstract
        type: rich-text
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 200
        description: "Abstract or summary of the publication"
      - name: keywords
        label: Keywords
        type: string
        list:
          min: 1
          max: 20
        description: "Research keywords and tags"
      - name: doi
        label: DOI
        type: string
        description: "Digital Object Identifier"
        validation:
          pattern: "^10\\.[0-9]{4,}/.+"
      - name: url
        label: External URL
        type: string
        description: "Link to published version"
        validation:
          pattern: "^https?://.+"

  # Team Members - Enhanced and aligned with actual content
  - name: members
    label: Team Members
    type: collection
    path: _members
    filename: "{name|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [name, role, status, email, order]
      primary: name
      sort:
        field: order
        direction: asc
      search: [name, role, research_interests]
      filters:
        - field: status
          label: Status
        - field: role
          label: Role
      group_by: status
    fields:
      - name: layout
        label: Layout
        type: string
        default: member
        hidden: true
      - name: name
        label: Full Name
        type: string
        required: true
        description: "Enter the person's full name (e.g., Prof. Dr. Gebhard Böckle)"
        validation:
          min_length: 2
          max_length: 100
      - name: role
        label: Role/Position
        type: select
        required: true
        options:
          "Professor & Group Leader": Professor & Group Leader
          "Postdoctoral Researcher": Postdoctoral Researcher
          "PhD Student": PhD Student
          "Master Student": Master Student
          "Bachelor Student": Bachelor Student
          "Secretary": Secretary
          "Former Member": Former Member
          "Alumni": Alumni
          "Guest Researcher": Guest Researcher
        description: "Academic or professional role"
      - name: status
        label: Status
        type: select
        options:
          active: Active Member
          alumni: Alumni
          former: Former Member
          inactive: Inactive
          visitor: Visitor
        default: active
        required: true
        description: "Current status of the team member"
      - name: photo
        label: Profile Photo
        type: image
        options:
          multiple: false
          max_size: 5242880
          accepted_types: [jpg, jpeg, png, webp]
        description: "Professional headshot or profile photo (recommended: 400x400px)"
      - name: order
        label: Display Order
        type: number
        default: 999
        hidden: true
        description: "Lower numbers appear first in listings"
      - name: email
        label: Email Address
        type: email
        description: "Professional email address"


  # Teaching & Courses - Enhanced with better course management
  - name: teaching
    label: Teaching & Courses
    type: collection
    path: _teaching
    filename: "{semester|slugify}-{title|slugify}.md"
    format: yaml-frontmatter
    exclude:
      - index.md
      - documents/
      - pdfs/
      - heidelberg-teaching-archive.md
      - past-teaching.md
    view:
      fields: [title, semester, instructor, course_type, active]
      primary: title
      sort:
        field: semester
        direction: desc
      search: [title, instructor, description]
      filters:
        - field: course_type
          label: Course Type
        - field: language
          label: Language
        - field: active
          label: Active
      group_by: semester
    fields:
      - name: layout
        label: Layout
        type: string
        default: teaching
        hidden: true
      - name: title
        label: Course Title
        type: string
        required: true
        description: "Full course title (e.g., Homological Algebra Seminar)"
        validation:
          min_length: 5
          max_length: 200
      - name: semester
        label: Semester
        type: string
        required: true
        description: "Semester (e.g., WS2024, SS2025)"
        validation:
          pattern: "^(WS|SS)[0-9]{4}$"
      - name: instructor
        label: Instructor(s)
        type: string
        required: true
        description: "Course instructor(s) (e.g., Prof. Dr. Böckle, Dr. Ferraro)"
      - name: course_type
        label: Course Type
        type: select
        options:
          lecture: Lecture (Vorlesung)
          seminar: Seminar
          exercise: Exercise
          tutorial: Tutorial
          workshop: Workshop
          lab: Laboratory
          colloquium: Colloquium
        default: seminar
        required: true
        description: "Type of course"
      - name: language
        label: Language
        type: select
        options:
          en: English
          de: German
          bilingual: Bilingual
        default: en
        required: true
        description: "Primary language of instruction"
      - name: description
        label: Course Description
        type: rich-text
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 150
        description: "Course overview and objectives"
      - name: active
        label: Currently Active
        type: boolean
        default: false
        description: "Is this course currently being taught?"

  # Research Areas - Enhanced with better organization
  - name: research
    label: Research Areas
    type: collection
    path: _research
    filename: "{title|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [title, description, featured, order]
      primary: title
      sort:
        field: order
        direction: asc
      search: [title, description, keywords]
      filters:
        - field: featured
          label: Featured
      group_by: featured
    fields:
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
      - name: title
        label: Research Area Title
        type: string
        required: true
        description: "Name of the research area (e.g., Arithmetic of Function Fields)"
        validation:
          min_length: 3
          max_length: 100
      - name: description
        label: Description
        type: rich-text
        required: true
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 200
        description: "Detailed description of the research area"
      - name: order
        label: Display Order
        type: number
        default: 999
        hidden: true
        description: "Lower numbers appear first"
      - name: featured
        label: Featured Research Area
        type: boolean
        default: false
        description: "Highlight this research area on the homepage"


 