media:
  input: assets/img
  output: /assets/img
  path: assets/img
  categories: [image]
  extensions: [jpg, jpeg, png, gif, svg, webp]

content:
  - name: members
    label: Team Members
    type: collection
    path: _members
    filename: "{name|slugify}.md"
    view:
      fields: [name, role, order, photo, email]
      sort:
        field: order
        direction: asc
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: role
        label: Role/Position
        type: string
        required: true
      - name: photo
        label: Profile Photo
        type: image
      - name: order
        label: Display Order
        type: number
        default: 999
      - name: email
        label: Email Address
        type: string
      - name: website
        label: Personal Website
        type: string
      - name: github
        label: GitHub Username
        type: string
      - name: orcid
        label: ORCID ID
        type: string
      - name: research_interests
        label: Research Interests
        type: rich-text
      - name: bio
        label: Biography
        type: rich-text

  - name: publications
    label: Publications
    type: collection
    path: _publications
    filename: "{year}-{title|slugify}.md"
    view:
      fields: [title, authors, year, publication_type, doi]
      sort:
        field: year
        direction: desc
    fields:
      - name: title
        label: Publication Title
        type: string
        required: true
      - name: authors
        label: Authors
        type: string
        required: true
      - name: publication_type
        label: Publication Type
        type: select
        options:
          - Journal Article
          - Conference Paper
          - Preprint
          - Book Chapter
          - Thesis
          - Technical Report
        default: Journal Article
      - name: year
        label: Publication Year
        type: number
        required: true
      - name: journal
        label: Journal/Conference
        type: string
      - name: publication_details
        label: Publication Details
        type: string
      - name: volume
        label: Volume
        type: string
      - name: issue
        label: Issue
        type: string
      - name: pages
        label: Pages
        type: string
      - name: doi
        label: DOI
        type: string
      - name: url
        label: URL
        type: string
      - name: abstract
        label: Abstract
        type: text
      - name: keywords
        label: Keywords
        type: string
        list: true
      - name: featured
        label: Featured Publication
        type: boolean
        default: false

  - name: teaching
    label: Teaching & Courses
    type: collection
    path: _teaching
    filename: "{semester|slugify}-{title|slugify}.md"
    view:
      fields: [title, semester, instructor]
      sort:
        field: semester
        direction: desc
    fields:
      - name: title
        label: Course Title
        type: string
        required: true
      - name: semester
        label: Semester
        type: string
        required: true
      - name: instructor
        label: Instructor(s)
        type: string
        required: true
      - name: course_type
        label: Course Type
        type: select
        options:
          - Lecture
          - Seminar
          - Exercise
          - Tutorial
          - Workshop
        default: Seminar
      - name: credits
        label: ECTS Credits
        type: number
      - name: language
        label: Language
        type: select
        options:
          - English
          - German
          - Bilingual
        default: English
      - name: description
        label: Course Description
        type: rich-text
      - name: syllabus
        label: Syllabus
        type: rich-text
      - name: materials
        label: Course Materials
        type: file
        list: true
      - name: active
        label: Currently Active
        type: boolean
        default: false

  - name: research
    label: Research Areas
    type: collection
    path: _research
    filename: "{title|slugify}.md"
    view:
      fields: [title, description]
      sort:
        field: title
        direction: asc
    fields:
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
      - name: title
        label: Research Area Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: order
        label: Display Order
        type: number
        default: 999
      - name: featured
        label: Featured Research Area
        type: boolean
        default: false
      - name: keywords
        label: Keywords
        type: string
        list: true
      - name: related_publications
        label: Related Publications
        type: reference
        collection: publications
        list: true

  - name: news
    label: News & Blog Posts
    type: collection
    path: _news
    filename: "{year}-{month}-{day}-{title|slugify}.md"
    view:
      fields: [title, date, published, categories]
      sort:
        field: date
        direction: desc
    fields:
      - name: layout
        label: Layout
        type: string
        default: post
        hidden: true
      - name: title
        label: Post Title
        type: string
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: published
        label: Published
        type: boolean
        default: true
      - name: categories
        label: Categories
        type: string
        list: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: excerpt
        label: Excerpt
        type: text
      - name: content
        label: Content
        type: rich-text
        required: true
      - name: featured_image
        label: Featured Image
        type: image

  - name: links
    label: Links & Resources
    type: collection
    path: _links
    filename: "{title|slugify}.md"
    view:
      fields: [title, category, url]
      sort:
        field: title
        direction: asc
    fields:
      - name: title
        label: Link Title
        type: string
        required: true
      - name: url
        label: URL
        type: string
        required: true
      - name: category
        label: Category
        type: string
      - name: order
        label: Display Order
        type: number
        default: 999
      - name: description
        label: Description
        type: text
      - name: featured
        label: Featured Link
        type: boolean
        default: false

  - name: config
    label: Site Configuration
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Website Description
        type: text
      - name: email
        label: Contact Email
        type: string
      - name: url
        label: Website URL
        type: string
      - name: twitter_username
        label: Twitter Username
        type: string
      - name: github_username
        label: GitHub Username
        type: string

components:
  contact_info:
    label: Contact Information
    fields:
      - name: email
        label: Email
        type: string
      - name: phone
        label: Phone
        type: string
      - name: office
        label: Office Location
        type: string
      - name: office_hours
        label: Office Hours
        type: text

  social_links:
    label: Social Media Links
    fields:
      - name: twitter
        label: Twitter
        type: string
      - name: github
        label: GitHub
        type: string
      - name: linkedin
        label: LinkedIn
        type: string
      - name: researchgate
        label: ResearchGate
        type: string

settings:
  content:
    merge: true 