# Enhanced Pages CMS Configuration for AG Computational Arithmetic Geometry
# This file configures the content management interface at https://app.pagescms.org/
# Updated January 2025 - Fully aligned with latest PagesCMS features and actual content

# Media Configuration
media:
  - name: images
    label: Images & Photos
    input: assets/img
    output: /assets/img
    path: assets/img
    categories: [image]
    extensions: [jpg, jpeg, png, gif, svg, webp]
    description: "Upload images for team members, research areas, and general website content"
  - name: documents
    label: Documents & PDFs
    input: assets/uploads
    output: /assets/uploads
    path: assets/uploads
    categories: [document]
    extensions: [pdf, doc, docx, ppt, pptx, xls, xlsx, txt, md, tex, bib]
    description: "Course materials, announcements, and research documents"


# Content Types Configuration
content:
  # Publications - NEW: Full collection management
  - name: publications
    label: Publications
    type: collection
    path: _publications
    filename: "{year}-{title|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [title, authors, year, type, status, featured]
      primary: title
      sort:
        field: year
        direction: desc
      search: [title, authors, abstract, keywords]
      filters:
        - field: type
          label: Publication Type
        - field: status
          label: Status
        - field: featured
          label: Featured
      group_by: year
    fields:
      - name: layout
        label: Layout
        type: string
        default: publication
        hidden: true
      - name: title
        label: Publication Title
        type: string
        required: true
        description: "Full title of the publication"
        validation:
          min_length: 5
          max_length: 500
      - name: authors
        label: Authors
        type: string
        required: true
        description: "Author names separated by commas"
        validation:
          min_length: 2
          max_length: 200
      - name: year
        label: Publication Year
        type: number
        required: true
        description: "Year of publication"
        validation:
          min: 1900
          max: 2030
      - name: type
        label: Publication Type
        type: select
        required: true
        options:
          values:
            - { label: Journal Article, value: "Journal Article" }
            - { label: Preprint, value: "Preprint" }
            - { label: Conference Paper, value: "Conference Paper" }
            - { label: Book, value: "Book" }
            - { label: Book Chapter, value: "Book Chapter" }
            - { label: Thesis, value: "Thesis" }
            - { label: Software, value: "Software" }
            - { label: Technical Report, value: "Technical Report" }
        default: "Journal Article"
        description: "Type of publication"
      - name: status
        label: Publication Status
        type: select
        options:
          values:
            - { label: Published, value: "Published" }
            - { label: Submitted, value: "Submitted" }
            - { label: Under Review, value: "Under Review" }
            - { label: In Preparation, value: "In Preparation" }
            - { label: Accepted, value: "Accepted" }
        default: "Published"
        description: "Current status of the publication"
      - name: journal
        label: Journal/Conference/Publisher
        type: string
        description: "Journal name, conference name, or publisher"
        validation:
          max_length: 200
      - name: abstract
        label: Abstract
        type: rich-text
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 200
        description: "Abstract or summary of the publication"
      - name: keywords
        label: Keywords
        type: string
        list:
          min: 1
          max: 20
        description: "Research keywords and tags"
      - name: doi
        label: DOI
        type: string
        description: "Digital Object Identifier"
        validation:
          pattern: "^10\\.[0-9]{4,}/.+"
      - name: url
        label: External URL
        type: string
        description: "Link to published version"
        validation:
          pattern: "^https?://.+"

  # Team Members - Enhanced and aligned with actual content
  - name: members
    label: Team Members
    type: collection
    path: _members
    filename: "{name|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [name, role, status, email, order]
      primary: name
      sort:
        field: order
        direction: asc
      search: [name, role, research_interests]
      filters:
        - field: status
          label: Status
        - field: role
          label: Role
      group_by: status
    fields:
      - name: layout
        label: Layout
        type: string
        default: member
        hidden: true
      - name: name
        label: Full Name
        type: string
        required: true
        description: "Enter the person's full name (e.g., Prof. Dr. Gebhard Böckle)"
        validation:
          min_length: 2
          max_length: 100
      - name: role
        label: Role/Position
        type: select
        required: true
        options:
          values:
            - { label: "Professor & Group Leader", value: "Professor & Group Leader" }
            - { label: "Postdoctoral Researcher", value: "Postdoctoral Researcher" }
            - { label: "PhD Student", value: "PhD Student" }
            - { label: "Master Student", value: "Master Student" }
            - { label: "Bachelor Student", value: "Bachelor Student" }
            - { label: "Secretary", value: "Secretary" }
            - { label: "Alumni", value: "Alumni" }
            - { label: "Guest Researcher", value: "Guest Researcher" }
        description: "Academic or professional role"
      - name: status
        label: Status
        type: select
        options:
          values:
            - { label: Active Member, value: active }
            - { label: Alumni, value: alumni }
            - { label: Former Member, value: former }
            - { label: Inactive, value: inactive }
            - { label: Visitor, value: visitor }
        default: active
        required: true
        description: "Current status of the team member"
      - name: photo
        label: Profile Photo
        type: image
        options:
          multiple: false
          max_size: 5242880
          accepted_types: [jpg, jpeg, png, webp]
        description: "Professional headshot or profile photo (recommended: 400x400px)"
      - name: order
        label: Display Order
        type: number
        default: 999
        hidden: true
        description: "Lower numbers appear first in listings"
      - name: email
        label: Email Address
        type: email
        description: "Professional email address"


  # Teaching & Courses - Enhanced with better course management
  - name: teaching
    label: Teaching & Courses
    type: collection
    path: _teaching
    filename: "{semester|slugify}-{title|slugify}.md"
    format: yaml-frontmatter
    exclude:
      - index.md
      - documents/
      - pdfs/
      - heidelberg-teaching-archive.md
      - past-teaching.md
    view:
      fields: [title, semester, instructor, course_type, active]
      primary: title
      sort:
        field: semester
        direction: desc
      search: [title, instructor, description]
      filters:
        - field: course_type
          label: Course Type
        - field: language
          label: Language
        - field: active
          label: Active
      group_by: semester
    fields:
      - name: layout
        label: Layout
        type: string
        default: teaching
        hidden: true
      - name: title
        label: Course Title
        type: string
        required: true
        description: "Full course title (e.g., Homological Algebra Seminar)"
        validation:
          min_length: 5
          max_length: 200
      - name: semester
        label: Semester
        type: select
        required: true
        description: "Select semester (add new if missing)"
        options:
          values:
            - label: SS2022
              value: SS2022
            - label: WS2022
              value: WS2022
            - label: SS2023
              value: SS2023
            - label: WS2023
              value: WS2023
            - label: SS2024
              value: SS2024
            - label: WS2024
              value: WS2024
            - label: SS2025
              value: SS2025
            - label: WS2025
              value: WS2025
            - label: SS2026
              value: SS2026
            - label: WS2026
              value: WS2026
            - label: SS2027
              value: SS2027
            - label: WS2027
              value: WS2027
          allowCustom: true
        validation:
          pattern: "^(WS|SS)[0-9]{4}$"
      - name: instructor
        label: Instructor(s)
        type: string
        required: true
        description: "Course instructor(s) (e.g., Prof. Dr. Böckle, Dr. Ferraro)"
      - name: course_type
        label: Course Type
        type: select
        options:
          values:
            - { label: Vorlesung, value: Vorlesung }
            - { label: Seminar, value: Seminar }
            - { label: Proseminar, value: Proseminar }
            - { label: Hauptseminar, value: Hauptseminar }
            - { label: Exercise, value: Exercise }
            - { label: Tutorial, value: Tutorial }
            - { label: Workshop, value: Workshop }
            - { label: Laboratory, value: Laboratory }
            - { label: Colloquium, value: Colloquium }
          allowCustom: true
        default: Seminar
        required: true
        description: "Type of course"
      - name: level
        label: Level
        type: select
        options:
          values:
            - { label: Bachelor, value: Bachelor }
            - { label: Master, value: Master }
            - { label: PhD, value: PhD }
            - { label: Mixed, value: Mixed }
          allowCustom: true
        description: "Intended audience level (optional)"
      - name: language
        label: Language
        type: select
        options:
          values:
            - { label: English, value: English }
            - { label: German, value: German }
            - { label: Bilingual, value: Bilingual }
          allowCustom: true
        default: English
        required: true
        description: "Primary language of instruction"
      - name: description
        label: Course Description
        type: rich-text
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 150
        description: "Course overview and objectives"
      - name: active
        label: Currently Active
        type: boolean
        default: false
        description: "Is this course currently being taught?"

  # Research Areas - Enhanced with better organization
  - name: research
    label: Research Areas
    type: collection
    path: _research
    filename: "{title|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [title, description, featured, order]
      primary: title
      sort:
        field: order
        direction: asc
      search: [title, description, keywords]
      filters:
        - field: featured
          label: Featured
      group_by: featured
    fields:
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
      - name: title
        label: Research Area Title
        type: string
        required: true
        description: "Name of the research area (e.g., Arithmetic of Function Fields)"
        validation:
          min_length: 3
          max_length: 100
      - name: description
        label: Description
        type: rich-text
        required: true
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 200
        description: "Detailed description of the research area"
      - name: order
        label: Display Order
        type: number
        default: 999
        hidden: true
        description: "Lower numbers appear first"
      - name: featured
        label: Featured Research Area
        type: boolean
        default: false
        description: "Highlight this research area on the homepage"


  # Links - External/internal resource links
  - name: links
    label: Useful Links
    type: collection
    path: _links
    filename: "{title|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [title, url, category]
      primary: title
      sort:
        field: title
        direction: asc
      search: [title, url, description, category]
    fields:
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: url
        label: URL
        type: string
        required: true
        validation:
          pattern: "^https?://.+"
      - name: category
        label: Category
        type: select
        options:
          values:
            - { label: Institution, value: Institution }
            - { label: Journal, value: Journal }
            - { label: Research Project, value: "Research Project" }
            - { label: Administrative, value: Administrative }
            - { label: Tooling, value: Tooling }
      - name: description
        label: Description
        type: rich-text
        options:
          toolbar: ["bold", "italic", "link", "list", "code"]
          height: 120

  # Static Pages - About, Contact, etc.
  - name: pages
    label: Static Pages
    type: collection
    path: _pages
    filename: "{title|slugify}.md"
    format: yaml-frontmatter
    view:
      fields: [title]
      primary: title
      sort:
        field: title
        direction: asc
      search: [title]
    fields:
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: permalink
        label: Permalink
        type: string
        description: "Optional custom permalink"
      - name: content
        label: Content
        type: markdown