media:
  - name: uploads
    label: All Uploads
    input: assets/uploads
    output: /assets/uploads
    extensions: ["png", "jpg", "jpeg", "gif", "svg", "pdf", "tex"]

content:
  - name: publications
    label: Publications
    path: _publications
    type: collection
    description: "Manage research papers and articles. Upload a PDF for each entry."
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: authors
        label: Authors
        type: string
        required: true
      - name: publication_type
        label: Publication Type
        type: select
        options:
          - Journal Article
          - Conference Paper
          - Preprint
          - Book
          - Book Chapter
          - Thesis
        required: true
      - name: publication_details
        label: "Journal, Conference, or Preprint Details"
        type: string
      - name: year
        label: Year
        type: number
        required: true
      - name: doi
        label: "DOI (Digital Object Identifier)"
        type: string
      - name: abstract
        label: Abstract
        type: rich-text
      - name: file
        label: PDF File
        type: file
        description: "Upload the publication PDF here."

  - name: members
    label: Team Members
    path: _members
    type: collection
    description: "Manage team members."
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: role
        label: Role
        type: string
        description: "e.g., Professor, PhD Student, Postdoc"
      - name: photo
        label: Photo
        type: image
      - name: email
        label: Email
        type: string
      - name: website
        label: Personal Website
        type: string
      - name: github
        label: GitHub Username
        type: string
      - name: bio
        label: Biography
        type: rich-text

  - name: resources
    label: Resources
    path: _resources
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: author
        label: Author
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: files
        label: Files
        type: file
        list: true
        required: false 