# Basic Jekyll Configuration for Phase 1
title: AG Computational Arithmetic Geometry
email: placeholder@math.uni-heidelberg.de
description: >- 
  Placeholder research group description. This is placeholder text for the initial website phase.
baseurl: ""
url: "https://placeholder-ag-comp-arith-geom.github.io"
twitter_username: placeholder
github_username: placeholder

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Europe/Berlin

# Theme settings - Keep theme switcher for Phase 1
theme_mode: auto
enable_darkmode: true
enable_theme_switcher: true

# Basic collections
collections_dir: .

collections:
  pages:
    output: true
    permalink: /:name/
  publications:
    output: true
  members:
    output: false
  resources:
    output: true

# Basic plugins only
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .private/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Reading Files
include:
  - .htaccess 

scholar:
  style: "apa"
  sort_by: "year"
  order: "descending"

# Analytics
analytics: 