name: DISABLED duplicate Pages workflows

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow file is intentionally disabled. Use pages.yml instead."